[pytest]
qt_api = pyqt5
testpaths = test_lancalc.py
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning
markers =
    qt_api: mark a test to specify the Qt API (e.g. pyqt5)